[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:exim4]
command=/usr/sbin/exim4 -bd -q30m
autostart=true
autorestart=true
stderr_logfile=/var/log/exim4/exim.err.log
stdout_logfile=/var/log/exim4/exim.out.log
user=Debian-exim

[program:dovecot]
command=/usr/sbin/dovecot -F
autostart=true
autorestart=true
stderr_logfile=/var/log/dovecot/dovecot.err.log
stdout_logfile=/var/log/dovecot/dovecot.out.log
user=root
