[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:opendkim]
command=/usr/sbin/opendkim -f -x /etc/opendkim.conf
autostart=false
autorestart=false
stdout_logfile=/var/log/supervisor/opendkim.out.log
stderr_logfile=/var/log/supervisor/opendkim.err.log

[program:exim4]
command=/usr/sbin/exim4 -bd -q30m
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/exim4.out.log
stderr_logfile=/var/log/supervisor/exim4.err.log
