#!/bin/bash
# Render exim4.conf template with values from /etc/exim4/dynamic/

set -e

CONFIG_DIR=/etc/exim4/dynamic
TEMPLATE=/etc/exim4/exim4.conf.template
OUTPUT=/var/lib/exim4/config.autogenerated

read_dynamic() {
    local file="$1"
    local fallback="$2"
    if [ -s "$file" ]; then
        tr -d '\n\r' < "$file"
    else
        echo "$fallback"
    fi
}

PRIMARY_HOSTNAME=$(read_dynamic "$CONFIG_DIR/primary_hostname" "smtp0.example.com")
QUALIFY_DOMAIN=$(read_dynamic "$CONFIG_DIR/qualify_domain" "")
if [ -z "$QUALIFY_DOMAIN" ] && [ -f "$CONFIG_DIR/domains" ]; then
    QUALIFY_DOMAIN=$(grep -vE '^[[:space:]]*(#|$)' "$CONFIG_DIR/domains" | head -1 | tr -d '\n\r')
fi
QUALIFY_DOMAIN=${QUALIFY_DOMAIN:-local.invalid}
DKIM_SELECTOR=$(read_dynamic "$CONFIG_DIR/dkim_selector" "mail")

# Build trusted DKIM key path map (avoids Exim "tainted filename" on dynamic paths)
DKIM_PATHS_FILE="$CONFIG_DIR/dkim_paths"
: > "$DKIM_PATHS_FILE"
if [ -f "$CONFIG_DIR/domains" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
        domain="${line#"${line%%[![:space:]]*}"}"
        domain="${domain%"${domain##*[![:space:]]}"}"
        [ -z "$domain" ] && continue
        [[ "$domain" == \#* ]] && continue
        echo "${domain}:/etc/opendkim/keys/${domain}/${DKIM_SELECTOR}.private" >> "$DKIM_PATHS_FILE"
    done < "$CONFIG_DIR/domains"
fi
chmod 644 "$DKIM_PATHS_FILE"

# Ensure dynamic files are readable by Exim (uid 100)
chmod 644 "$CONFIG_DIR"/*.txt 2>/dev/null || true
for f in domains primary_hostname qualify_domain dkim_selector rate_10m rate_1h rate_1d; do
    [ -f "$CONFIG_DIR/$f" ] && chmod 644 "$CONFIG_DIR/$f"
done
for f in rate_tiers.json rate_assignments.json; do
    [ -f "$CONFIG_DIR/$f" ] && chmod 644 "$CONFIG_DIR/$f"
done

sed \
    -e "s|@@PRIMARY_HOSTNAME@@|${PRIMARY_HOSTNAME}|g" \
    -e "s|@@QUALIFY_DOMAIN@@|${QUALIFY_DOMAIN}|g" \
    -e "s|@@DKIM_SELECTOR@@|${DKIM_SELECTOR}|g" \
    "$TEMPLATE" > "$OUTPUT"

echo "Rendered Exim config: hostname=${PRIMARY_HOSTNAME}, qualify=${QUALIFY_DOMAIN}, dkim=${DKIM_SELECTOR}"
