#!/bin/bash
# Install/configure fail2ban + firewalld helpers for exim-docker.
# Blocks AUTH abuse via DOCKER-USER (Docker published ports). Does not ban
# normal MX EHLO/QUIT scanners.
#
# Usage:
#   ./helper-scripts/setup-firewall.sh
#   EXIM_DOCKER_ROOT=/opt/exim-docker ./helper-scripts/setup-firewall.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="${EXIM_DOCKER_ROOT:-$ROOT}"
FW_DIR="${ROOT}/data/firewall"
LOG_DIR="${ROOT}/data/log"

echo "=== exim-docker firewall setup ==="
echo "  Root: $ROOT"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root."
  exit 1
fi

mkdir -p "$FW_DIR" "$LOG_DIR"
touch "$LOG_DIR/mainlog" "$LOG_DIR/rejectlog"

# SELinux: fail2ban (fail2ban_t) cannot read admin_home_t under /root — label as var_log_t
if command -v semanage >/dev/null 2>&1 && [ "$(getenforce 2>/dev/null)" != "Disabled" ]; then
  echo "Applying SELinux fcontext var_log_t on ${LOG_DIR}..."
  semanage fcontext -a -t var_log_t "${LOG_DIR}(/.*)?" 2>/dev/null \
    || semanage fcontext -m -t var_log_t "${LOG_DIR}(/.*)?" 2>/dev/null \
    || true
  restorecon -Rv "$LOG_DIR" >/dev/null || true
fi

# Seed store if missing (include WHMCS IP when present in smtp allow)
if [ ! -f "$FW_DIR/blocked_ips.json" ]; then
  cat > "$FW_DIR/blocked_ips.json" <<'EOF'
{
  "whitelist": [
    "127.0.0.1",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "173.208.139.117"
  ],
  "blocked": []
}
EOF
  echo "Created $FW_DIR/blocked_ips.json"
fi

echo "Installing fail2ban..."
if command -v dnf >/dev/null 2>&1; then
  dnf install -y fail2ban fail2ban-firewalld >/dev/null
elif command -v apt-get >/dev/null 2>&1; then
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban >/dev/null
else
  echo "No dnf/apt — install fail2ban manually."
  exit 1
fi

install -m 644 "${ROOT}/fail2ban/filter.d/exim-docker-auth.conf" /etc/fail2ban/filter.d/exim-docker-auth.conf
install -m 644 "${ROOT}/fail2ban/action.d/docker-user.conf" /etc/fail2ban/action.d/docker-user.conf

# Jail with absolute log paths
cat > /etc/fail2ban/jail.d/exim-docker.local <<EOF
# Generated by setup-firewall.sh — AUTH abuse only (not normal MX)
[exim-docker-auth]
enabled = true
filter = exim-docker-auth
backend = auto
maxretry = 5
findtime = 10m
bantime = 12h
action = docker-user[name=exim-docker-auth]
logpath = ${LOG_DIR}/mainlog
          ${LOG_DIR}/rejectlog
EOF

# firewalld: ensure mail ports (Docker still publishes; this helps host policy)
if systemctl is-active --quiet firewalld; then
  echo "Opening firewalld ports for mail stack..."
  for p in 25 80 443 465 587 993 8090; do
    firewall-cmd --permanent --add-port="${p}/tcp" >/dev/null 2>&1 || true
  done
  firewall-cmd --reload >/dev/null || true
else
  echo "firewalld not active — skipping port opens (DOCKER-USER bans still work)."
fi

# Sync agent + systemd units
install -m 755 "${ROOT}/helper-scripts/firewall-sync.sh" /usr/local/sbin/exim-docker-firewall-sync

cat > /etc/systemd/system/exim-docker-firewall.service <<EOF
[Unit]
Description=exim-docker firewall sync (manual bans + fail2ban status)
After=network.target fail2ban.service docker.service

[Service]
Type=oneshot
Environment=EXIM_DOCKER_ROOT=${ROOT}
ExecStart=/usr/local/sbin/exim-docker-firewall-sync
EOF

cat > /etc/systemd/system/exim-docker-firewall.path <<EOF
[Unit]
Description=Watch exim-docker firewall store for changes

[Path]
PathModified=${FW_DIR}/blocked_ips.json
PathExists=${FW_DIR}/sync.request

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/exim-docker-firewall.timer <<EOF
[Unit]
Description=Refresh exim-docker firewall status every minute

[Timer]
OnBootSec=30s
OnUnitActiveSec=60s
AccuracySec=5s
Unit=exim-docker-firewall.service

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now fail2ban
systemctl enable --now exim-docker-firewall.path
systemctl enable --now exim-docker-firewall.timer
systemctl restart fail2ban
sleep 1
/usr/local/sbin/exim-docker-firewall-sync || true

echo ""
echo "=== Done ==="
echo "  fail2ban jail: exim-docker-auth (5 hits / 10m → 12h ban)"
echo "  Action:        iptables DOCKER-USER DROP"
echo "  Panel store:   ${FW_DIR}/blocked_ips.json"
echo "  Status file:   ${FW_DIR}/status.json"
echo ""
fail2ban-client status exim-docker-auth || true
